app/blueprints/stoichiometry/models.py
from app import db, login
from datetime import datetime
from flask_login import UserMixin
from app.blueprints.authentication.models import User

# db table for saving stoich queries by user_id
class StoichQueries(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    q_reactants = db.Column(db.String)
    q_products = db.Column(db.String)
    s_reactants = db.Column(db.String)
    s_products = db.Column(db.String)
    created_on = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.ForeignKey('user.id'))

    # create a method that will allow for display via api
    def to_dict(self):
        data = {
            'user_id' : self.user_id,
            'q_reactants' : self.q_reactants,
            'q_products' : self.q_products,
            's_reactants' : self.s_reactants,
            's_products' : self.s_products,
            'created_on' : self.created_on
        }
        return data

    def __repr__(self):
        return f'Solution: {self.s_reactants} = {self.s_products}' 

app/blueprints/stoichiometry/forms.py
from wtforms import StringField, SubmitField
from flask_wtf import FlaskForm

# form for stoichiometry
class two_part_reaction(FlaskForm):
    reactants = StringField()
    products = StringField()
    submit = SubmitField('Submit Query')

app/blueprints/stoichiometry/__init__.py
from flask import Blueprint

bp = Blueprint('stoichiometry', __name__, url_prefix='/stoichiometry')

from .import models, routes

app/blueprints/stoichiometry/routes.py
from .import bp as stoichiometry
from chempy import balance_stoichiometry, Substance, mass_fractions
from .forms import two_part_reaction
from flask_login import current_user, login_required
from .models import StoichQueries
from flask import flash, redirect, render_template, url_for, request
from app import db
from sqlalchemy import desc


# route to balance an equation
@stoichiometry.route('/', methods=['GET', 'POST'])
@login_required
def do_stoichiometry():
    # set up an instance of the form
    form = two_part_reaction()

    reac = None
    prod = None
    solution = None

    if form.validate_on_submit():
        # collect the data from the form into a dictionary
        data = {
            'reactants' : [_.strip() for _ in request.form.get('reactants').split(',')],
            'products' : [_.strip() for _ in request.form.get('products').split(',')]
        }

        # plug in the info to the balance_stoichiometry method
        # Try/except block so if theres an error the page doesnt break
        Checked = False
        while not Checked:
            try:
                reac, prod = balance_stoichiometry(data['reactants'], data['products'])

                # create a variable to save the solution
                solution = (f'{str(reac)[13:-2]} = {str(prod)[13:-2]}')
                s_reac = str(reac)[13:-2]
                s_prod = str(prod)[13:-2]
                # create an instance of the StoichQuery table
                s = StoichQueries(q_reactants = data['reactants'], q_products=data['products'], s_products=s_prod, s_reactants=s_reac, user_id=current_user.id)
                # save the instance to the database
                db.session.add(s)
                db.session.commit()
                Checked = True
            except ValueError:
                flash("There was an error in query, solution cannot be determined. Please try again", 'danger')
                return redirect(url_for('stoichiometry.do_stoichiometry'))

        flash(f'Query Submitted!', 'success')
        return redirect(url_for('stoichiometry.do_stoichiometry'))

    # send the data to the HTML page
    content = {
        'Query' : StoichQueries.query.filter_by(user_id=current_user.id).order_by(desc('created_on')).first(),
        'form' : form
    }
    return render_template('stoichiometry.html', **content)

@stoichiometry.route('/stoichqueries')
@login_required
def stoich_queries():
    if current_user.is_authenticated:
        my_queries = current_user.stoich_queries
    else:
        my_queries = []
    print(my_queries)
    return render_template('stoichqueries.html', queries=my_queries)

app/templates/index.html
{% extends 'layout.html'%}

{% block title %}
{{ super() }} | Homepage
{% endblock %}

{% block content %}
<!-- 
    A breif summary of why this was created, target demographic, and uses

    A list of features offered by this app - with links to their appropriate pages

    Citations to the resources used

    LinkedIn plug to personal page
 -->
{% endblock %}

app/templates/layout.html
{% set navigation_bar = [
    ('/', 'index', 'Homepage'),
    ('/stoichiometry', 'stoichiometry', 'Stoichiometry'),
    ('/stoichqueries', 'stoichqueries', 'StoichQueries'),
    ('/molarmass', 'molarmass', 'MolarMass'),
    ('/mmqueries', 'mmqueries', 'MMQueries')
     
] -%}

{% set active_page = active_page|default('index') -%}

<!doctype html>
<html lang="en">
  <head>
    <title>
        {% block title %}
            Chemathstry
        {% endblock %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" >
    <link rel="stylesheet" href="../static/css/main.css">
    <link rel="stylesheet" href="../static/css/header.css">
    {% endblock %}
    
  </head>
  <body>
      <main>
          <div class="container">
        <header>
            {% include './partials/header.html' %}
        </header>
        </div>

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for c, m in messages %}
            <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong> {{ m }} </strong>
            </div>
            {% endfor %}
            {% endif%}
            {% endwith %}
            <div class="container">
            {% block content %}
            {% endblock %}
            </div>
        </main>
        <footer>
            {% include './partials/footer.html' %}
        </footer>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/login.html
{% extends 'layout.html'%}

{% block title %}
    {{ super() }} | Login
{% endblock %}

{% block content %} 
<h3>
    Login to your account below! 
</h3>
<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('authentication.login') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.email(class='form-control', placeholder='Email') }}
                {%for error in form.email.errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{error}}</strong>
                    </div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password(class='form-control', placeholder='Password') }}
            </div>
                {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <a href="{{url_for('authentication.register') }}">Not registered? Click Here!</a>

    </div>
</div>
{% endblock %}

app/templates/mmqueries.html
{% extends 'layout.html'%}
{% set active_page='MMQueries'-%}

{% block title %}
{{ super() }} | My Queries
{% endblock %}

{% block content %}
<div class="row">
    <div class="containter-col-md-12">
        <ul class="list-group">
            {% for q in queries %}
            <li class="list-group-item">
                Molar mass of {{ q.q_MM }} = {{ q.s_MM }}
                <cite>
                    &mdash; @ {{ moment(q.created_on).fromNow() }}
                </cite>
            </li>
            {% endfor %}
            <h3>All queries shown!</h3>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/molarmass.html
{% extends 'layout.html'%}
{% set active_page='stoichiometry' -%}


{% block title %}
{{ super() }} | MolarMass
{% endblock %}

{% block content %}
<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('molarmass.get_MM') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                Your molecule here in this format - AL2O3
                {{ form.get_MM(class='form-control', placeholder="Query") }}
            </div>
            </div>
            {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>

{% if Query %} {{Query}} {% endif %}
<a href="{{ url_for('molarmass.mm_queries') }}">Want to see all of your previous queries and their
    solutions?</a>
{% endblock %}

app/templates/register.html
{% extends 'layout.html'%}

{% block title %}
{{ super() }} | Register
{% endblock %}

{% block content %}
<h3>
    Welcome to Chemathstry!! Register your account below!
</h3>

<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('authentication.register') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.first_name(class='form-control', placeholder='First Name') }}
            </div>
            <div class="form-group">
                {{ form.last_name(class='form-control', placeholder='Last Name') }}
            </div>
            <div class="form-group">
                {{ form.email(class='form-control', placeholder='Email') }}
                {%for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{error}}</strong>
                </div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password(class='form-control', placeholder='Password') }}
            </div>
            <div class="form-group">
                {{ form.confirm_password(class='form-control', placeholder='Confirm Password') }}
            </div>
            <div class="form-group">
                {{ form.accept_tos(class='form-check-label')}} I agree to the Terms of Service
            </div>
            {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/stoichiometry.html
{% extends 'layout.html'%}
{% set active_page='stoichiometry' -%}


{% block title %}
{{ super() }} | Stoichiometery
{% endblock %}

{% block content %}
<div class="row">
    <div class='col-md-6'>
        <form action="{{ url_for('stoichiometry.do_stoichiometry') }}" method='POST' novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                Enter your reactants here in this format - NH4ClO4, Al 
                {{ form.reactants(class='form-control', placeholder="Reactants") }}
            </div>
            <div class="form-group">
                Enter your products here in this format - Al2O3, HCl, H2O, N2
                {{ form.products(class='form-control', placeholder="Products") }}
            </div>
            {{ form.submit(class='btn btn-outline-primary btn-block') }}
        </form>
    </div>
</div>

{% if Query %} {{Query}} {% endif %}
<a href="{{ url_for('stoichiometry.stoich_queries') }}" >Want to see all of your previous queries and their solutions?</a>
{% endblock %}

app/templates/stoichqueries..html
{% extends 'layout.html'%}
{% set active_page='StoichQueries'-%}

{% block title %}
{{ super() }} | My Queries
{% endblock %}

{% block content %}
<div class="row">
    <div class="containter-col-md-12">
        <ul class="list-group">
            {% for q in queries %}
            <li class="list-group-item">
               {{ q.q_reactants = q.q_products balances out to q.s_reactants = q.s_products }}
                <cite>
                    &mdash; @ {{ moment(q.created_on).fromNow() }}
                </cite>
            </li>
            {% endfor %}
            {% else %}
            <h3>All queries shown!</h3>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/stoichqueries.html
{% extends 'layout.html'%}
{% set active_page='StoichQueries'-%}

{% block title %}
{{ super() }} | My Queries
{% endblock %}

{% block content %}
<div class="row">
    <div class="containter-col-md-12">
        <ul class="list-group">
            {% for q in queries %}
            <li class="list-group-item">
               {{ q.q_reactants }} = {{ q.q_products }} balances out to {{q.s_reactants}} = {{ q.s_products }}
                <cite>
                    &mdash; @ {{ moment(q.created_on).fromNow() }}
                </cite>
            </li>
            {% endfor %}
            <h3>All queries shown!</h3>
        </ul>
    </div>
</div>
{% endblock %}